" An example for a vimrc file.
"
" Maintainer:	Bram Moolenaar <Bram@vim.org>
" Last change:	2019 Dec 17
"
" To use it, copy it to
"	       for Unix:  ~/.vimrc
"	      for Amiga:  s:.vimrc
"	 for MS-Windows:  $VIM\_vimrc
"	      for Haiku:  ~/config/settings/vim/vimrc
"	    for OpenVMS:  sys$login:.vimrc

" When started as "evim", evim.vim will already have done these settings, bail
" out.
if v:progname =~? "evim"
  finish
endif

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file (restore to previous version)
  if has('persistent_undo')
    set undofile	" keep an undo file (undo changes after closing)
  endif
endif

if &t_Co > 2 || has("gui_running")
  " Switch on highlighting the last used search pattern.
  set hlsearch
endif

" Put these in an autocmd group, so that we can delete them easily.
augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78
augroup END

" DEPRECATED: Old, manual package manager
" 
" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
" if has('syntax') && has('eval')
"   packadd! matchit
" endif

set termguicolors

if has("mouse_sgr")
    set ttymouse=sgr
else
    set ttymouse=xterm2
end
let g:markdown_recommended_style = 0
set expandtab
set shiftwidth=2 smarttab
set number
set relativenumber
set ruler
set clipboard=unnamed
set nobackup
set noundofile
set ignorecase
set smartcase

" Mappings
:function ToggleWrap()
: if (&wrap == 1)
:   set nowrap
: else
:   set wrap
: endif
:endfunction

map <F9> :call ToggleWrap()<CR>
map! <F9> ^[:call ToggleWrap()<CR>

" In insert or command mode, move normally by using Ctrl
noremap! <C-h> <Left>
noremap! <C-j> <Down>
noremap! <C-k> <Up>
noremap! <C-l> <Right>

nnoremap # *
nnoremap + #

call plug#begin()
" List your plugins here
Plug 'tpope/vim-sensible'
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'airblade/vim-gitgutter'
Plug 'andymass/vim-matchup'
Plug 'tomtom/tcomment_vim'
call plug#end()

:colorscheme catppuccin
:highlight Normal NONE
:highlight LineNr guifg=green
:highlight LineNrAbove guifg=#f9e2af
:highlight LineNrBelow guifg=#a6e3a1

" gitgutter settings
":highlight SignColumn ctermbg=none
set updatetime=100
let g:gitgutter_highlight_lines = 1
let g:mapleader=" "
