# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# zsh auto suggestions
# Widgets that accept the entire suggestion
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(
        end-of-line
        vi-forward-char
        vi-end-of-line
        vi-add-eol
)

# Widgets that accept the suggestion as far as the cursor moves
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=(
        forward-word
        forward-char
        vi-forward-word
        vi-forward-word-end
        vi-forward-blank-word
        vi-forward-blank-word-end
)

#Key bindings
bindkey "^[[5~" history-beginning-search-backward # Page Up
bindkey "^[[6~" history-beginning-search-forward  # Page Down

bindkey '^f' vi-forward-word
bindkey '^b' vi-backward-word

# Aliases
alias sort=gsort
alias .=..
alias __='_ -s'

if [[ -x /usr/local/bin/gls ]]; then
  alias l='/usr/local/bin/gls -lAh --group-directories-first --color'
else
  alias l='/bin/ls -lAh --group-directories-first --color'
fi

alias f='find . -iname'
alias fa='sudo find / -iname'

alias du='du -sch * | sort -h'
alias df='df -H'

alias g=googler
alias piff="pstorm diff"

alias p='cd ~/Projekte/PHP/Aldi/Preisabfragen'
