# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Source env specific profile stuff
if [[ -s "${ZDOTDIR:-$HOME}/.profile" ]]; then
  source "${ZDOTDIR:-$HOME}/.profile"
fi

# Source zsh command completions
if [[ -s "/usr/local/share/zsh/site-functions/aws_zsh_completer.sh" ]]; then
  source /usr/local/share/zsh/site-functions/aws_zsh_completer.sh
fi

# Customize to your needs...

# zsh auto suggestions
# Widgets that accept the entire suggestion
ZSH_AUTOSUGGEST_ACCEPT_WIDGETS=(
        end-of-line
        vi-forward-char
        vi-end-of-line
        vi-add-eol
)

# Widgets that accept the suggestion as far as the cursor moves
ZSH_AUTOSUGGEST_PARTIAL_ACCEPT_WIDGETS=(
        forward-word
        forward-char
        vi-forward-word
        vi-forward-word-end
        vi-forward-blank-word
        vi-forward-blank-word-end
)

#Key bindings
bindkey "^[[5~" history-beginning-search-backward # Page Up
bindkey "^[[6~" history-beginning-search-forward  # Page Down


bindkey '^f' vi-forward-word
bindkey '^b' vi-backward-word
bindkey '^x' fzf-cd-widget

# Aliases
alias __='_ -s'
alias 7=7z

alias bu="brew upgrade && echo '🍻  \e[1mBrew update finished 🍻 Upgrading Casks:\e[0m' && brew cask upgrade"
alias c=cd
alias df='df -H'
alias du='setopt CSH_NULL_GLOB && du -sch .[!.]* * |sort -h && unsetopt CSH_NULL_GLOB'

alias f='fd'
alias fzf='fzf --preview "head -100 {}"'

alias g=git
alias ga='git add'
alias gb='git branch'
alias gc='git checkout'
alias gco='git commit'
alias gd='git difftool'
alias gdg='git difftool -g'
alias gf='git fetch'
alias gl='git log'
alias gm='git merge'
alias gp='git pull'
alias gpu='git push'
alias gr='git remote'
alias gs='git status'
alias gst='git stash'
alias gsm='git submodule'

alias gg='googler --colors Bjdgxy'
alias iiff='idea diff'

if [[ -s /usr/local/bin/gls ]]; then
  alias l='/usr/local/bin/gls -lAh --group-directories-first --color'
else
  alias l='/bin/ls -lAh --group-directories-first --color'
fi

alias p='cd ~/Projekte/iOS/H-Hotels'

if [[ -s /usr/bin/pbcopy ]]; then
  alias cpy='/usr/bin/pbcopy'
fi

if [[ -s /usr/bin/pbpaste ]]; then
  alias pst='/usr/bin/pbpaste'
fi

alias piff='pstorm diff'
alias pip=pip3
alias python=python3
alias rg='rg -i'
alias rr='rm -rf'
alias sl=subl
[ -s /usr/local/bin/gsort ] && alias sort=gsort
alias x='exa -lah --group-directories-first --git'

# Functions
function ds() {
	open "dash://b:$*"
}

function ff() {
	sudo fd $* /
}

# Additonal external scripts and auto completions
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh

eval "`pip completion --zsh`"
compctl -K _pip_completion pip3
