#!/bin/zsh
setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

if [[ -x /usr/local/bin/zsh ]]; then
  chsh -s /usr/local/bin/zsh
else
  chsh -s /bin/zsh
fi
exec zsh
